name: Pipeline

on:
  push:
    branches: [ "CI/CD" ]
  pull_request:
    branches: [ "CI/CD" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Test with Gradle
        env:
          PORT: 8080
        run: ./gradlew test


  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build with Gradle
        env:
          PORT: 8080
        run: ./gradlew -x check build
      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: built-jar
          path: build/libs/esop-trading-0.1-all.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Download JAR
        uses: actions/download-artifact@v3
        with:
          name: built-jar
      - name: Create SSH key file
        env:
          EC2_ACCESS_KEY: ${{ secrets.EC2_ACCESS_KEY }}
          USER: ${{ secrets.USER }}
          EC2_ADDRESS: ${{ secrets.EC2_ADDRESS }}
        run: echo $EC2_ACCESS_KEY  > key.pem
      - name: Copy JAR to instance
        run: scp -o StrictHostKeyChecking=no -i key.pem esop-trading-0.1-all.jar $USER@$EC2_ADDRESS:~/
      - name: Run JAR
        run: scp -o StrictHostKeyChecking=no -i key.pem $USER@$EC2_ADDRESS 'sudo java -jar esop-trading-0.1-all.jar'